version: '3.8'

services:
  web:
    build: .
    image: meex1999/web_recepi:1.0  # Добавьте здесь имя образа и тег
    command: gunicorn mydjangoprj.wsgi:application --bind 0.0.0.0:8010
    volumes:
      #- ./static:/app/staticfiles
      - static_volume:/app/staticfiles  # Общий том для статических файлов
      - ./media:/app/media
    environment:
      - DEBUG=False
    expose:
      - "8010"  # Открываем порт для внутреннего использования

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Монтируем конфиг Nginx
      #- ./static:/app/staticfiles  # Путь к статическим файлам
      - static_volume:/app/staticfiles  # Общий том для статических файлов
      - ./media:/app/media    # Путь к медиафайлам
    ports:
      - "80:80"  # Публикуем порт 80 на хосте
    depends_on:
      - web  # Указываем, что Nginx зависит от сервиса web
# Определяем общий том
volumes:
  static_volume:  # Здесь мы объявляем общий том